services:
  flask-app:
    image: bogocasino:latest
    build: ./flask-app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    env_file:
      - .env
    environment:
      - MONGO_USER=${MONGO_USERNAME}
      - MONGO_PASS=${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - database:/data/db

networks:
  default:
    driver: bridge

volumes:
  database: