services:
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    env_file:
      - flask.env
    depends_on:
      - mongo
      - craps
    networks:
      - casino-network

  craps:
    build: ./craps
    ports:
      - "5001:5001"
    env_file:
      - craps.env
    networks:
      - casino-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - casino-network
    volumes:
      - mongo-data:/data/db

networks:
  casino-network:

volumes:
  mongo-data: