name: CI/CD Badge
on: 
  pull_request:
    types: [opened, closed]
  push:
    branches: [main]
jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Enter Directory
        run: |
          cd flask-app
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run the tests
        working-directory: ./flask-app
        run: |
          python -m pip install pipenv
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest
  build_push:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: DockerHub Login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build Image and Push
        uses: docker/build-push-action@v2
        with:
          context: ./flask-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bogocasino:latest
  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - name: Deployment to Digital Ocean
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSW}}
          envs: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}, ${{secrets.IMAGENAME}}, ${{secrets.DOCKER_USERNAME}}
          script: |
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            docker stop ${{secrets.IMAGENAME}}
            docker rm ${{secrets.IMAGENAME}}
            docker run -d \
            --restart always \
            --name ${{secrets.IMAGENAME}} \
            ${{secrets.DOCKER_USERNAME}}/${{secrets.IMAGENAME}}:latest
            docker compose up --build -d
